# Generated by Django 3.1.3 on 2021-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_bridge', 'data_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='scan_timeout',
            field=models.IntegerField(default=2),
        ),
    ]
