# Generated by Django 3.1.3 on 2021-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pki_bridge', 'data_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='domain',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='template',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='csr',
            field=models.TextField(),
        ),
    ]
